### ISSUE TITLE
[BUG] Intermediate overlay which blocks interaction of windows below scratchpad when scratchapad are started with keybindings

### ISSUE THREAD

**Issue by samtrek** [hyprland-community/pyprland#149]
**Pyprland version**
2.4.1

**Describe the bug**
Intermediate freezing of screen due to a gray overlay of windows below scratchpad when a new scratchpad is started with a  keybinding 

**To Reproduce**
1. remove lazy from scratchpad configs
2. Start a the scratchpad with the assigned keybinding (these may require multiple start and stop to catch the bug or repeatedly toggle scratchpad )
3. The window below the scratchpad is grayed out due to an overlay and cannot be interacted with, in a multiple monitor setup, the alternate monitor is not affected.
4. To remove the gray overlay , repeatedly toggle scratchpads 
**Expected behavior**
Their should not be a blank gray overlay blocking interaction with other windows when scratchpads are toggled, or when the are started

**Comment by fdev31** [comment]
I mostly use multi-monitor setups so it must be something specific to your use case.
Can you be a bit more specific, is it happening with every scratchpad? Any monitor layout or specific conditions etc.... ?

Additionally, try to format your bug report so it can be readable, and provide the logs of the failed scenario along with the explanations.

**Comment by samtrek** [comment]
It also happens on my latpop which is not connected to a monitor, albeit less frequently once in a while when the scratchpad is started from with a keybinding, an it shows an overlay which blocks other activities until, another or a couple of scratchpads are called

**Comment by samtrek** [comment]
- The log 
             
         ipc - Logger "ipc" initialized // common.py:205
                  startup - Logger "startup" initialized // common.py:205
                     pypr - Logger "pypr" initialized // common.py:205
                     pypr - Loading /home/samtrek/.config/hypr/pyprland.toml // command.py:114
                 pyprland - Logger "pyprland" initialized // common.py:205
                 pyprland - version // ipc.py:102
                 pyprland - activeworkspace // ipc.py:102
                 pyprland - monitors // ipc.py:102
                 pyprland - configured // command.py:179
              scratchpads - Logger "scratchpads" initialized // common.py:205
              scratchpads - monitors (CACHE HIT) // ipc.py:99
              scratchpads - keyword ['windowrule float,^(thunar)$', 'windowrule workspace special:scratch_thunar silent,^(thunar)$', 'windowrule move 200% 377,^(thunar)$', 'windowrule size 504 270,^(thunar)$'] // ipc.py:145
              scratchpads - thunar is not running, starting... // __init__.py:266
              scratchpads - scratch thunar (thunar) has pid 3276405 // __init__.py:287
              scratchpads - starting thunar // __init__.py:238
              scratchpads - ==> Wait for thunar spawning // __init__.py:192
              scratchpads - clients // ipc.py:102
              scratchpads - clients // ipc.py:102
              scratchpads - clients // ipc.py:102
              scratchpads - clients // ipc.py:102
              scratchpads - clients // ipc.py:102
              scratchpads - clients // ipc.py:102
              scratchpads - => thunar client (proc:3276405, addr:0x5d4cd0a971e0) detected on time // __init__.py:203
              scratchpads - keyword windowrule unset,^(thunar)$ // ipc.py:145
              scratchpads - configured // command.py:179
           toggle_special - Logger "toggle_special" initialized // common.py:205
           toggle_special - configured // command.py:179
            menus adapter - Logger "menus adapter" initialized // common.py:205
           shortcuts_menu - Logger "shortcuts_menu" initialized // common.py:205
           shortcuts_menu - configured // command.py:179
                     pypr - ================================[ initialized ]================================= // command.py:381
                 pyprland - event_activewindowv2('5d4cd088f950',) // command.py:202
                 pyprland - active_window = 0x5d4cd088f950 // pyprland.py:78
              scratchpads - event_activewindowv2('5d4cd088f950',) // command.py:202
              scratchpads - event_openwindow('5d4cd0a971e0,special:scratch_thunar silent,thunar,Downloads - Thunar',) // command.py:202
              scratchpads - clients // ipc.py:102
              scratchpads - dispatch movetoworkspacesilent special:scratch_thunar,address:0x5d4cd0a971e0 // ipc.py:145
              scratchpads - run_toggle('yazi',) // command.py:202
              scratchpads - visibility_check: ('', '') == ('6: \uf120', 'DVI-I-2') // __init__.py:472
              scratchpads - yazi visibility: False and False // __init__.py:498
              scratchpads - Showing yazi // __init__.py:575
              scratchpads - scratch yazi ([term_classed] yazi -e yazi ~/) has pid 3285933 // __init__.py:287
              scratchpads - ==> Wait for yazi spawning // __init__.py:192
                 pyprland - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - active_window = 0x5d4cd0a80e90 // pyprland.py:78
              scratchpads - clients // ipc.py:102
                 pyprland - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - active_window = 0x5d4cd0a80e90 // pyprland.py:78
              scratchpads - => yazi client (proc:3285933, addr:0x5d4cd0a80e90) detected on time // __init__.py:203
              scratchpads - clients (CACHE HIT) // ipc.py:99
              scratchpads - dispatch movetoworkspacesilent special:scratch_yazi,address:0x5d4cd0a80e90 // ipc.py:145
                 pyprland - event_activewindowv2('5d4cd088f950',) // command.py:202
                 pyprland - active_window = 0x5d4cd088f950 // pyprland.py:78
              scratchpads - monitors // ipc.py:102
              scratchpads - dispatch resizewindowpixel exact 504 270,address:0x5d4cd0a80e90 // ipc.py:145
              scratchpads - clients // ipc.py:102
              scratchpads - dispatch ['moveworkspacetomonitor special:scratch_yazi DVI-I-2', 'movetoworkspacesilent 6: \uf120 \uf0c7,address:0x5d4cd0a80e90', 'alterzorder top,address:0x5d4cd0a80e90'] // ipc.py:145
              scratchpads - dispatch ['movewindowpixel exact 2156 377,address:0x5d4cd0a80e90'] // ipc.py:145
              scratchpads - dispatch focuswindow address:0x5d4cd0a80e90 // ipc.py:145
                 pyprland - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - active_window = 0x5d4cd0a80e90 // pyprland.py:78
              scratchpads - dispatch pin address:0x5d4cd0a80e90 // ipc.py:145
              scratchpads - event_activewindowv2('5d4cd0a80e90',) // command.py:202
              scratchpads - event_openwindow('5d4cd0a80e90,6: \uf120,yazi,kitty',) // command.py:202
              scratchpads - event_activewindowv2('5d4cd0a80e90',) // command.py:202
              scratchpads - event_activewindowv2('5d4cd088f950',) // command.py:202
              scratchpads - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - active_window = 0x5d4cd0a80e90 // pyprland.py:78
              scratchpads - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - active_window = 0x5d4cd0a80e90 // pyprland.py:78
              scratchpads - event_activewindowv2('5d4cd0a80e90',) // command.py:202
              scratchpads - event_closewindow('5d4cd0a80e90',) // command.py:202
                 pyprland - event_activewindowv2('5d4cd088f950',) // command.py:202
                 pyprland - active_window = 0x5d4cd088f950 // pyprland.py:78
              scratchpads - event_activewindowv2('5d4cd088f950',) // command.py:202
              scratchpads - run_toggle('yazi',) // command.py:202
              scratchpads - visibility_check: ('6: \uf120', 'DVI-I-2') == ('6: \uf120', 'DVI-I-2') // __init__.py:472
              scratchpads - yazi visibility: True and True // __init__.py:498
              scratchpads - clients // ipc.py:102
              scratchpads - Showing yazi // __init__.py:575
              scratchpads - clients (CACHE HIT) // ipc.py:99
              scratchpads - clients (CACHE HIT) // ipc.py:99
              scratchpads - scratch yazi ([term_classed] yazi -e yazi ~/) has pid 3286909 // __init__.py:287
              scratchpads - ==> Wait for yazi spawning // __init__.py:192
                 pyprland - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - active_window = 0x5d4cd0a80e90 // pyprland.py:78
              scratchpads - clients // ipc.py:102
              scratchpads - clients (CACHE HIT) // ipc.py:99
              scratchpads - => yazi client (proc:3286909, addr:0x5d4cd0a80e90) detected on time // __init__.py:203
              scratchpads - clients (CACHE HIT) // ipc.py:99
              scratchpads - dispatch movetoworkspacesilent special:scratch_yazi,address:0x5d4cd0a80e90 // ipc.py:145
                 pyprland - event_activewindowv2('5d4cd088f950',) // command.py:202
                 pyprland - active_window = 0x5d4cd088f950 // pyprland.py:78
              scratchpads - monitors // ipc.py:102
              scratchpads - dispatch resizewindowpixel exact 504 270,address:0x5d4cd0a80e90 // ipc.py:145
              scratchpads - clients // ipc.py:102
              scratchpads - dispatch ['moveworkspacetomonitor special:scratch_yazi DVI-I-2', 'movetoworkspacesilent 6: \uf120 \uf0c7,address:0x5d4cd0a80e90', 'alterzorder top,address:0x5d4cd0a80e90'] // ipc.py:145
              scratchpads - dispatch ['movewindowpixel exact 2156 377,address:0x5d4cd0a80e90'] // ipc.py:145
              scratchpads - dispatch focuswindow address:0x5d4cd0a80e90 // ipc.py:145
                 pyprland - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - active_window = 0x5d4cd0a80e90 // pyprland.py:78
              scratchpads - dispatch pin address:0x5d4cd0a80e90 // ipc.py:145
              scratchpads - event_activewindowv2('5d4cd0a80e90',) // command.py:202
              scratchpads - event_openwindow('5d4cd0a80e90,6: \uf120,yazi,kitty',) // command.py:202
              scratchpads - event_activewindowv2('5d4cd088f950',) // command.py:202
              scratchpads - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - active_window = 0x5d4cd0a80e90 // pyprland.py:78
              scratchpads - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - active_window = 0x5d4cd0a80e90 // pyprland.py:78
              scratchpads - event_activewindowv2('5d4cd0a80e90',) // command.py:202
              scratchpads - run_toggle('yazi',) // command.py:202
              scratchpads - visibility_check: ('6: \uf120', 'DVI-I-2') == ('6: \uf120', 'DVI-I-2') // __init__.py:472
              scratchpads - yazi visibility: True and True // __init__.py:498
              scratchpads - clients // ipc.py:102
              scratchpads - clients (CACHE HIT) // ipc.py:99
              scratchpads - Hiding yazi // __init__.py:785
              scratchpads - dispatch ['movewindowpixel 564 0,address:0x5d4cd0a80e90'] // ipc.py:145
              scratchpads - dispatch pin address:0x5d4cd0a80e90 // ipc.py:145
              scratchpads - dispatch movetoworkspacesilent special:scratch_yazi,address:0x5d4cd0a80e90 // ipc.py:145
                 pyprland - event_activewindowv2('5d4cd088f950',) // command.py:202
                 pyprland - active_window = 0x5d4cd088f950 // pyprland.py:78
              scratchpads - event_activewindowv2('5d4cd088f950',) // command.py:202
              scratchpads - run_toggle('yazi',) // command.py:202
              scratchpads - visibility_check: ('6: \uf120', 'DVI-I-2') == ('6: \uf120', 'DVI-I-2') // __init__.py:472
              scratchpads - yazi visibility: False and False // __init__.py:498
              scratchpads - Showing yazi // __init__.py:575
              scratchpads - clients // ipc.py:102
              scratchpads - clients (CACHE HIT) // ipc.py:99
              scratchpads - monitors // ipc.py:102
              scratchpads - dispatch resizewindowpixel exact 504 270,address:0x5d4cd0a80e90 // ipc.py:145
              scratchpads - clients (CACHE HIT) // ipc.py:99
              scratchpads - dispatch ['moveworkspacetomonitor special:scratch_yazi DVI-I-2', 'movetoworkspacesilent 6: \uf120,address:0x5d4cd0a80e90', 'alterzorder top,address:0x5d4cd0a80e90'] // ipc.py:145
              scratchpads - dispatch ['movewindowpixel exact 2156 377,address:0x5d4cd0a80e90'] // ipc.py:145
              scratchpads - dispatch focuswindow address:0x5d4cd0a80e90 // ipc.py:145
                 pyprland - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - active_window = 0x5d4cd0a80e90 // pyprland.py:78
              scratchpads - dispatch pin address:0x5d4cd0a80e90 // ipc.py:145
              scratchpads - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - active_window = 0x5d4cd0a80e90 // pyprland.py:78
              scratchpads - event_activewindowv2('5d4cd0a80e90',) // command.py:202
              scratchpads - event_closewindow('5d4cd0a80e90',) // command.py:202
                 pyprland - event_activewindowv2('5d4cd088f950',) // command.py:202
                 pyprland - active_window = 0x5d4cd088f950 // pyprland.py:78
              scratchpads - event_activewindowv2('5d4cd088f950',) // command.py:202
              scratchpads - run_toggle('yazi',) // command.py:202
              scratchpads - visibility_check: ('6: \uf120', 'DVI-I-2') == ('6: \uf120', 'DVI-I-2') // __init__.py:472
              scratchpads - yazi visibility: True and True // __init__.py:498
              scratchpads - clients // ipc.py:102
              scratchpads - Showing yazi // __init__.py:575
              scratchpads - clients (CACHE HIT) // ipc.py:99
              scratchpads - clients (CACHE HIT) // ipc.py:99
              scratchpads - scratch yazi ([term_classed] yazi -e yazi ~/) has pid 3288152 // __init__.py:287
              scratchpads - ==> Wait for yazi spawning // __init__.py:192
                 pyprland - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - active_window = 0x5d4cd0a80e90 // pyprland.py:78
              scratchpads - clients // ipc.py:102
              scratchpads - clients (CACHE HIT) // ipc.py:99
              scratchpads - => yazi client (proc:3288152, addr:0x5d4cd0a80e90) detected on time // __init__.py:203
              scratchpads - clients (CACHE HIT) // ipc.py:99
              scratchpads - dispatch movetoworkspacesilent special:scratch_yazi,address:0x5d4cd0a80e90 // ipc.py:145
                 pyprland - event_activewindowv2('5d4cd088f950',) // command.py:202
                 pyprland - active_window = 0x5d4cd088f950 // pyprland.py:78
              scratchpads - monitors // ipc.py:102
              scratchpads - dispatch resizewindowpixel exact 504 270,address:0x5d4cd0a80e90 // ipc.py:145
              scratchpads - clients // ipc.py:102
              scratchpads - dispatch ['moveworkspacetomonitor special:scratch_yazi DVI-I-2', 'movetoworkspacesilent 6: \uf120 \uf0c7,address:0x5d4cd0a80e90', 'alterzorder top,address:0x5d4cd0a80e90'] // ipc.py:145
              scratchpads - FAILED b'okError in moveActiveToWorkspaceSilent, invalid valueok' // ipc.py:166
              scratchpads - dispatch ['movewindowpixel exact 2156 377,address:0x5d4cd0a80e90'] // ipc.py:145
              scratchpads - dispatch focuswindow address:0x5d4cd0a80e90 // ipc.py:145
                 pyprland - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - active_window = 0x5d4cd0a80e90 // pyprland.py:78
                 pyprland - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - active_window = 0x5d4cd0a80e90 // pyprland.py:78
              scratchpads - dispatch pin address:0x5d4cd0a80e90 // ipc.py:145
              scratchpads - event_activewindowv2('5d4cd0a80e90',) // command.py:202
              scratchpads - event_openwindow('5d4cd0a80e90,6: \uf120,yazi,kitty',) // command.py:202
              scratchpads - event_activewindowv2('5d4cd088f950',) // command.py:202
              scratchpads - event_activewindowv2('5d4cd0a80e90',) // command.py:202
              scratchpads - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - active_window = 0x5d4cd0a80e90 // pyprland.py:78
              scratchpads - event_activewindowv2('5d4cd0a80e90',) // command.py:202
              scratchpads - run_toggle('yazi',) // command.py:202
              scratchpads - visibility_check: ('6: \uf120', 'DVI-I-2') == ('6: \uf120', 'DVI-I-2') // __init__.py:472
              scratchpads - yazi visibility: True and True // __init__.py:498
              scratchpads - clients // ipc.py:102
              scratchpads - clients (CACHE HIT) // ipc.py:99
              scratchpads - Hiding yazi // __init__.py:785
              scratchpads - dispatch ['movewindowpixel 564 0,address:0x5d4cd0a80e90'] // ipc.py:145
              scratchpads - dispatch pin address:0x5d4cd0a80e90 // ipc.py:145
              scratchpads - dispatch movetoworkspacesilent special:scratch_yazi,address:0x5d4cd0a80e90 // ipc.py:145
                 pyprland - event_activewindowv2('',) // command.py:202
                 pyprland - no active window // pyprland.py:74
              scratchpads - event_activewindowv2('',) // command.py:202
              scratchpads - run_toggle('yazi',) // command.py:202
              scratchpads - visibility_check: ('6: \uf120', 'DVI-I-2') == ('6: \uf120', 'DVI-I-2') // __init__.py:472
              scratchpads - yazi visibility: False and False // __init__.py:498
              scratchpads - Showing yazi // __init__.py:575
              scratchpads - clients // ipc.py:102
              scratchpads - clients (CACHE HIT) // ipc.py:99
              scratchpads - monitors // ipc.py:102
              scratchpads - dispatch resizewindowpixel exact 504 270,address:0x5d4cd0a80e90 // ipc.py:145
              scratchpads - clients (CACHE HIT) // ipc.py:99
              scratchpads - dispatch ['moveworkspacetomonitor special:scratch_yazi DVI-I-2', 'movetoworkspacesilent 6: \uf120,address:0x5d4cd0a80e90', 'alterzorder top,address:0x5d4cd0a80e90'] // ipc.py:145
                 pyprland - event_activewindowv2('5d4cd088f950',) // command.py:202
                 pyprland - active_window = 0x5d4cd088f950 // pyprland.py:78
              scratchpads - dispatch ['movewindowpixel exact 2156 377,address:0x5d4cd0a80e90'] // ipc.py:145
              scratchpads - dispatch focuswindow address:0x5d4cd0a80e90 // ipc.py:145
                 pyprland - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - active_window = 0x5d4cd0a80e90 // pyprland.py:78
              scratchpads - dispatch pin address:0x5d4cd0a80e90 // ipc.py:145
              scratchpads - event_activewindowv2('5d4cd088f950',) // command.py:202
              scratchpads - event_activewindowv2('5d4cd0a80e90',) // command.py:202
                 pyprland - event_activewindowv2('5d4cd088f950',) // command.py:202
                 pyprland - active_window = 0x5d4cd088f950 // pyprland.py:78
              scratchpads - event_activewindowv2('5d4cd088f950',) // command.py:202

**Comment by fdev31** [comment]
Can you also provide your config?
It's only when `lazy=false` ?

**Comment by fdev31** [comment]
I am afraid I can't reproduce it, did you test different hyprland versions to see if the problem depends on it?

**Comment by samtrek** [comment]
I found out that the bug can be replicated if process_tracking = false is set in the config, and the overlay does not appear when not set at all, tested for kitty and foot (thinking maybe it was terminal related issue)

[scratchpads.btop]
animation = "fromLeft"
command = "kitty --class btop -e btop"
match_by = "class"
class = "btop"
size = "499px 414px"
max_size = "1920px 100%"
position = "2% 59%"
process_tracking = false

**Comment by fdev31** [comment]
Still not? I can't reproduce the issue on my side... (sorry, I forgot to tell you, I tested again today) and I believe this is a bug with Hyprland... can't you reproduce the same by starting & stopping btop in kitty very often without using a scratchpad ?

**Comment by fdev31** [comment]
Indeed I can't replicate and believe this has to do with Hyprland... If you like I can help you make a sequence to reproduce the issue (even though it's not reproducible 100%....).
Closing since I don't see how I can fix such in scratchpads, maybe a workaround is possible, if we make a script that is able to repeat the issue, we can introduce delays and see which sequence of commands create the race condition...
Reply here (even if closed) or use the discussion if you want to try that option.

**Comment by samtrek** [comment]
Yes I am totally open towards that, if you can make the script I will run it and send the logs/outputs back to you.

**Comment by fdev31** [comment]
Before that, it would be needed that you update to the latest version of Hyprland and Pyprland...
If you do so, reopen the ticket with the relevant logs (after update).
There is a chance this issue has been solved with the latest versions.

**Comment by samtrek** [comment]
The latest git version `2.4.5-32` seems to have solved this issue after a long while, however on the main version  `2.4.5` the issue still persists.
